server:
  port: 8081
  
spring:
  application:
    name: Zuul-Api-Gateway
    
eureka:
  instance:
    hostname: localhost

zuul:
  routes:
      flight-search:
        url: http://localhost:9001
      user-login:
        url: http://localhost:9002
      user-signup:
        url: http://localhost:9003