server:
  port: 8081
  
spring:
  application:
    name: Zuul-Api-Gateway
    
eureka:
  instance:
    hostname: localhost

zuul:
  routes:
      user-service:
        url: http://localhost:9001
      admin-service:
        url: http://localhost:9002